export const food = [
  {
    name: 'artichoke',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },
      { month: 'May', quality: 'stored/dried/frozen' },
      { month: 'June', quality: 'stored/dried/frozen' },
      { month: 'July', quality: 'stored/dried/frozen' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'stored/dried/frozen' },
      { month: 'December', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'asparagus',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
    ],
  },
  {
    name: 'beans',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },
      { month: 'May', quality: 'stored/dried/frozen' },
      { month: 'June', quality: 'stored/dried/frozen' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'stored/dried/frozen' },
      { month: 'November', quality: 'stored/dried/frozen' },
      { month: 'December', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'beets',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },
      { month: 'May', quality: 'stored/dried/frozen' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'broccoli',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
    ],
  },
  {
    name: 'brussel sprouts',
    category: 'Vegetable',
    season: [
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'cabbage green',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'cabbage savory & red',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh/stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'carrots',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh/stored/dried/frozen' },
      { month: 'February', quality: 'fresh/stored/dried/frozen' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'cauliflower',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'celery',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'chard, swiss',
    category: 'Vegetable',
    season: [
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'corn',
    category: 'Vegetable',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'cucumber',
    category: 'Vegetable',
    season: [
      { month: 'February', quality: 'greenhouse grown' },
      { month: 'March', quality: 'greenhouse grown' },
      { month: 'April', quality: 'greenhouse grown' },
      { month: 'May', quality: 'greenhouse grown' },
      { month: 'June', quality: 'greenhouse grown' },
      { month: 'July', quality: 'fresh/greenhouse grown' },
      { month: 'August', quality: 'fresh/greenhouse grown' },
      { month: 'September', quality: 'fresh/greenhouse grown' },
      { month: 'October', quality: 'greenhouse grown' },
    ],
  },
  {
    name: 'fennel (bulb)',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'garlic',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'greenhouse grown' },
      { month: 'February', quality: 'greenhouse grown' },
      { month: 'March', quality: 'greenhouse grown' },
      { month: 'April', quality: 'greenhouse grown' },
      { month: 'May', quality: 'greenhouse grown' },
      { month: 'June', quality: 'greenhouse grown' },
      { month: 'July', quality: 'greenhouse grown' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'greenhouse grown' },
      { month: 'December', quality: 'greenhouse grown' },
    ],
  },
  {
    name: 'kale',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh' },
      { month: 'February', quality: 'fresh' },
      { month: 'March', quality: 'fresh' },
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'leeks',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh' },
      { month: 'February', quality: 'fresh' },

      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'lettuce',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
    ],
  },
  {
    name: 'mustard greens',
    category: 'Vegetable',
    season: [
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
    ],
  },
  {
    name: 'onions - green',
    category: 'Vegetable',
    season: [
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
  {
    name: 'onions - red & yellow',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh/stored/dried/frozen' },
      { month: 'February', quality: 'fresh/stored/dried/frozen' },
      { month: 'March', quality: 'fresh/stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },
      { month: 'May', quality: 'stored/dried/frozen' },
      { month: 'June', quality: 'stored/dried/frozen' },
      { month: 'July', quality: 'stored/dried/frozen' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'parsnips',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'fresh/stored/dried/frozen' },
      { month: 'February', quality: 'fresh/stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'peas',
    category: 'Vegetable',
    season: [
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
    ],
  },
  {
    name: 'peppers',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'greenhouse grown' },
      { month: 'May', quality: 'greenhouse grown' },
      { month: 'June', quality: 'greenhouse grown' },
      { month: 'July', quality: 'greenhouse grown' },
      { month: 'August', quality: 'fresh/greenhouse grown' },
      { month: 'September', quality: 'fresh/greenhouse grown' },
      { month: 'October', quality: 'fresh/greenhouse grown' },
    ],
  },
  {
    name: 'potatoes - new',
    category: 'Vegetable',
    season: [
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
    ],
  },
  {
    name: 'potatoes - red, russet, yellow',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },

      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'potatoes - white',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },

      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'pumpkin',
    category: 'Vegetable',
    season: [
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'radishes',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'rhubarb field',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'rutabagas',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },

      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'salad greens',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
    ],
  },
  {
    name: 'shallots',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },

      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'stored/dried/frozen' },
      { month: 'October', quality: 'stored/dried/frozen' },
      { month: 'November', quality: 'stored/dried/frozen' },
      { month: 'December', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'spinach',
    category: 'Vegetable',
    season: [
      { month: 'April', quality: 'fresh' },
      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'squash - summer',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'stored/dried/frozen' },
      { month: 'October', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'squash - winter',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },

      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'tomatoes',
    category: 'Vegetable',
    season: [
      { month: 'March', quality: 'greenhouse grown' },
      { month: 'April', quality: 'greenhouse grown' },
      { month: 'May', quality: 'greenhouse grown' },
      { month: 'June', quality: 'greenhouse grown' },
      { month: 'July', quality: 'fresh/greenhouse grown' },
      { month: 'August', quality: 'fresh/greenhouse grown' },
      { month: 'September', quality: 'fresh/greenhouse grown' },
      { month: 'October', quality: 'fresh/greenhouse grown' },
      { month: 'November', quality: 'greenhouse grown' },
    ],
  },
  {
    name: 'turnip - white',
    category: 'Vegetable',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },

      { month: 'May', quality: 'fresh' },
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'zucchini',
    category: 'Vegetable',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'apples',
    category: 'Fruits',
    season: [
      { month: 'January', quality: 'stored/dried/frozen' },
      { month: 'February', quality: 'stored/dried/frozen' },
      { month: 'March', quality: 'stored/dried/frozen' },
      { month: 'April', quality: 'stored/dried/frozen' },

      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'apricots',
    category: 'Fruits',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'blackberries',
    category: 'Fruits',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'blueberries',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
  {
    name: 'cherries',
    category: 'Fruits',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'crab apples',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'stored/dried/frozen' },
      { month: 'December', quality: 'stored/dried/frozen' },
    ],
  },
  {
    name: 'cranberries',
    category: 'Fruits',
    season: [
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'currants',
    category: 'Fruits',
    season: [{ month: 'July', quality: 'fresh' }],
  },
  {
    name: 'gooseberries',
    category: 'Fruits',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
    ],
  },
  {
    name: 'grapes',
    category: 'Fruits',
    season: [{ month: 'September', quality: 'fresh' }],
  },
  {
    name: 'kiwi',
    category: 'Fruits',
    season: [
      { month: 'January', quality: 'fresh' },

      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'melons',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
  {
    name: 'nectarines',
    category: 'Fruits',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'peaches',
    category: 'Fruits',
    season: [{ month: 'August', quality: 'fresh' }],
  },
  {
    name: 'pears',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
      { month: 'November', quality: 'fresh' },
      { month: 'December', quality: 'fresh' },
    ],
  },
  {
    name: 'plums',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
  {
    name: 'prunes',
    category: 'Fruits',
    season: [
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
  {
    name: 'quince',
    category: 'Fruits',
    season: [
      { month: 'September', quality: 'fresh' },
      { month: 'October', quality: 'fresh' },
    ],
  },
  {
    name: 'raspberries',
    category: 'Fruits',
    season: [
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
    ],
  },
  {
    name: 'saskatoon berries',
    category: 'Fruits',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
    ],
  },
  {
    name: 'strawberries',
    category: 'Fruits',
    season: [
      { month: 'June', quality: 'fresh' },
      { month: 'July', quality: 'fresh' },
      { month: 'August', quality: 'fresh' },
      { month: 'September', quality: 'fresh' },
    ],
  },
];
